version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: user123
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@example.com
      PGADMIN_DEFAULT_PASSWORD: user123
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
