default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: active_record_reflection_study_development
  url: postgresql://pguser:user123@localhost:5432

test:
  <<: *default
  database: active_record_reflection_study_test
  url: postgresql://pguser:user123@localhost:5432

production:
  <<: *default
  database: active_record_reflection_study_production
  url: postgresql://pguser:user123@localhost:5432
